### PR TITLE
Release Engineering PR 1: Search Strategy

### PR DESCRIPTION
**Pull request by jessetilro**
**Group** Awesome Analytics Agency

In this first PR, we set up our chapter about Release Engineering. We write about the search strategy we used for obtaining Release Engineering related papers. We also include references to all relevant papers that we found.

### CODE REVIEW

**Comment by gousiosg** [comment]
Good job! You need to come up with RQs _before_ you start your investigation.

**Comment by Guillembonet** [comment]
Very effective and well-documented search strategy.

**Comment by fletna** [comment]
Reads well, good job on the search query too.

**Comment by lsikkes** [comment]
Good research and a well readable document!

**Comment by AyushiRastogi** [comment]
I read through the search strategy. Sounds good to me!

**Pull request merged**
